### ISSUE TITLE
Trinket support not working

### ISSUE THREAD

**Issue by josemunoz18** [TerraformersMC/Campanion#181]
I modified the ./config/campanion.json config file and set "trinkets_backpack_support": true
But still using the chest slot instead of the back slot.
Version Campanion v4.1.1+fabric for 1.19.2

**Comment by Wyn-Price** [comment]
Ah yes trinkets support was temporarily disabled - I can try and get it back tomorrow :)

**Comment by maddoodles** [comment]
It looks like it's still not working, did you ever get around to re-enabling it?

**Comment by MAGGen-hub** [comment]
How can I manualy re-enable it??? I need my armor slot! 
P.S. Oh... You already enabled it... 
Okay I will build 4.1.3 manualy on my PC...

**Comment by MAGGen-hub** [comment]
Well... Guess It will be harder than I thought... But well...

**Comment by MAGGen-hub** [comment]
Codding done... Creating Pull request...

**Comment by MAGGen-hub** [comment]
Done: https://github.com/TerraformersMC/Campanion/pull/188
Please check and merge if possible.
Looks cursed but works. (Only for fabric...)

**Comment by MAGGen-hub** [comment]
[temp-release.zip](https://github.com/TerraformersMC/Campanion/files/11082597/temp-release.zip)
Temporal release... You can unpack it to mods folder if you don't want to wait for actual release. May be buggy. Use at your own risk.

**Comment by Piraj** [comment]
as far as I tried this it does not seem to work, backpacks still dont go into the backpack slot
